### ISSUE TITLE
OpenCV failed to install

### ISSUE THREAD

**Issue by IvRogoz** [cgtinker/BlendArMocap#44]
Hello,

Ive started the Blender with admin privilege's but get this error ?

Installing collected packages: opencv-python
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\Blender\\3.1\\python\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

**Comment by cgtinker** [comment]
Hey there,

I guess it's an issue due to permissions. While you should have them as admin, there is probably something in your filesystem holding you back. Check this link on how to change permissions (in this case mainly the blender folder and the  'D:\Blender\3.1\python\Lib\site-packages\cv2\cv2.pyd' file are most likely having some permission setting which lead to the issue)
https://answers.microsoft.com/en-us/windows/forum/all/im-administrator-but-am-getting-denied-access-to/b0bd1447-2896-4a16-ad9d-7953e41a4a30

**Comment by cgtinker** [comment]
> Hello,
> 
> Ive started the Blender with admin privilege's but get this error ?
> 
> Installing collected packages: opencv-python ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\Blender\3.1\python\Lib\site-packages\cv2\cv2.pyd' Consider using the `--user` option or check the permissions.

is your issue already solved by now?
If not, could you try the build from the development branch? v1.5.1.

**Comment by cgtinker** [comment]
If you still face issues, please refer to #131
