### ISSUE TITLE
Wrong feet constrains by default.

### ISSUE THREAD

**Issue by CGI-Fox** [cgtinker/BlendArMocap#68]
Making a walking motion capture the feets don´t move correctly, I fix this changing the Locked Track constraint options and adding a Child Of constraint. After this the feets move correctly befote this the feets only stay onto the floor with a rotation motion.

If you have the same issue;

1.In pose mode select the feet bone (The same with the Inversed Kinematics)

2.Add a Child of constraint and select the "cgt_foot_driver.R" or "cgt_foot_driver.L" depending on the feet that you select, move this constraint upside the Locked Track constraint.

3.In the Locked Track constraint options select the "cgt_foot_driver.R" or "cgt_foot_driver.L" depending on the feet that you select, and in the Track Axis option find the correct one, this will put the foot to the right direction.

4.Now you can see that the foot don´t stay in the floor.

**Comment by cgtinker** [comment]
Which version of Blendarmocap are you using?

Did U transfer the leg animation? (When you have the pose collection selected there should be a transfer legs btn)

ATM working on an update, I think in some version I kept on transferring the foot track to constraints even if the leg animation is not getting transferred. 
Will be fixed in the upcoming version.

**Comment by CGI-Fox** [comment]
I using the last one, development mode, I enable the legs transfer.

**Comment by cgtinker** [comment]
just rechecked, in the dev build the feet locked track constraints have been active even if the "leg transfer" bool wasn't set. Should be fixed now.
