### ISSUE TITLE
not install in blender 3.1, install dependency not working properly

### ISSUE THREAD

**Issue by dipakn** [cgtinker/BlendArMocap#74]
the dependency have installation problem

**Comment by VisionaryMind** [comment]
Dependencies install fine in Blender 3.1 (when run with elevated permissions), however BlenderAR tab is empty. Has it been tested with 3.1?

**Comment by dipakn** [comment]
well my processor is ryzen 7 , gpu: nvidia 1660 super, 500gb ssd, blender 3.1, 16gb ram

**Comment by dipakn** [comment]
i tryed to much to install dependency , but did't work.

**Comment by dipakn** [comment]
operating system: windows 10,

**Comment by cgtinker** [comment]
Please toggle the system console and provide me the log message. 
To do so, navigate in blender to 'window' and choose select 'toggle system console'. Then copy the message and paste it here.

**Comment by dipakn** [comment]
Read prefs: C:\Users\X3\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
Reloading external rigs...
Reloading external metarigs...
BlendArMocap-main - Initializing...
BlendArMocap-main - add-on path: C:\Users\X3\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main
BlendArMocap-main - blender bin: C:\Program Files\Blender Foundation\Blender 3.2\blender.exe, blender version: (3, 2, 1)
BlendArMocap-main - python exe: C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\bin\python.EXE
Registing BlendArMocap

Try to access dependencies
The 'opencv_contrib_python' distribution was not found and is required by the application
opencv-contrib-python>=4.5.5.64 (None, None)
The 'protobuf' distribution was not found and is required by the application
protobuf>=3.11.4,<=3.20.0 (None, None)
The 'mediapipe' distribution was not found and is required by the application
mediapipe>=0.8.10 (None, None)

**Comment by cgtinker** [comment]
Did U start blender as admin and pressed the install dependencies button in the add-on settings?

**Comment by AuraNETinfo** [comment]
I can't install the dependencies and use Blneder on my Linux Ubuntu. Even logging in with admin privileges. The errors shown in the image below appear.

BlendArMocap-main - Initializing...
BlendArMocap-main - add-on path: /root/.config/blender/3.2/scripts/addons/BlendArMocap-main
BlendArMocap-main - blender bin: /snap/blender/2578/blender, blender version: (3, 2, 1)
BlendArMocap-main - python exe: /snap/blender/2578/3.2/python/bin/python3.10
Traceback (most recent call last):
File "/snap/blender/2578/3.2/scripts/modules/addon_utils.py", line 335, in enable
mod = import(module_name)
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/init.py", line 40, in
reload_modules()
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/init.py", line 36, in reload_modules
cgt_imports.manage_imports()
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_imports.py", line 84, in manage_imports
import_module(module)
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_imports.py", line 51, in import_module
importlib.import_module(f"{PACKAGE_NAME}{module}")
File "/snap/blender/2578/3.2/python/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/ui_registration.py", line 22, in
from . import ui_properties, ui_panels, pref_operators, pref_panels, ui_operators
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/ui_panels.py", line 21, in
from . import pref_operators
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/pref_operators.py", line 24, in
from ..utils import dependencies
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/utils/dependencies.py", line 410, in
for is_installed, corrupted_dependency in analyze_dependencies(required_dependencies):
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/utils/dependencies.py", line 356, in analyze_dependencies
if not is_package_installed(_dependency):
File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/utils/dependencies.py", line 116, in is_package_installed
package = importlib.util.find_spec(_dependency.name)
AttributeError: module 'importlib' has no attribute 'util'
addon_utils.disable: BlendArMocap-main not disabled
BlendArMocap-main - Initializing...
BlendArMocap-main - blender bin: /snap/blender/2578/blender, blender version: (3, 2, 1)
BlendArMocap-main - python exe: /snap/blender/2578/3.2/python/bin/python3.10
Registing BlendArMocap

Try to access dependencies
REGISTRATION FAILED: REQUIRED MODULE NOT FOUND
Attempting to install pip.
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmpx7d4bt7i
Requirement already satisfied: setuptools in /root/.local/lib/python3.10/site-packages (58.1.0)
Requirement already satisfied: pip in /root/.local/lib/python3.10/site-packages (21.2.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Attempting to install: opencv-contrib-python>=4.5.5.64
['/snap/blender/2578/3.2/python/bin/python3.10', '-m', 'pip', 'install', '--no-cache-dir', 'opencv-contrib-python>=4.5.5.64']
/snap/blender/2578/3.2/python/bin/python3.10: No module named pip
Cannot install opencv-contrib-python>=4.5.5.64.
Attempting to install: protobuf>=3.11.4,<=3.20.0
['/snap/blender/2578/3.2/python/bin/python3.10', '-m', 'pip', 'install', '--no-cache-dir', 'protobuf>=3.11.4,<=3.20.0']
/snap/blender/2578/3.2/python/bin/python3.10: No module named pip
Cannot install protobuf>=3.11.4,<=3.20.0.
Attempting to install: mediapipe>=0.8.10
['/snap/blender/2578/3.2/python/bin/python3.10', '-m', 'pip', 'install', '--no-cache-dir', 'mediapipe>=0.8.10']
/snap/blender/2578/3.2/python/bin/python3.10: No module named pip
Cannot install mediapipe>=0.8.10.
BlendArMocap-main - Initializing...
BlendArMocap-main - blender bin: /snap/blender/2578/blender, blender version: (3, 2, 1)
BlendArMocap-main - python exe: /snap/blender/2578/3.2/python/bin/python3.10
BlendArMocap-main - Dependencies installed: False

**Comment by cgtinker** [comment]
I've updated the add-on, the current version is available on the main branch. I'll soon create an official release.

Linux sadly doesn't come with pip, consider to checkout the docs for manual setup:
[documentation](https://cgtinker.github.io/BlendArMocap/installation/manual_dependency_installation.html)
